export default {
    chevronLeft: require('./chevron-left.png'),
    calendar: require('./calendar.png'),
    roundCheckBlue: require('./round-check-blue.png'),
    faceId: require('./face-id.png'),
    google: require('./google.png'),
    rightRounded: require('./right-rounded.png'),
    greenCheck: require('./green-check.png'),
    redClose: require('./red-close.png'),
    recordingIcon: require('./recording-icon.png'),
    arrowLeftRound: require('./arrow-left-round.png'),
    roundCheckBlueBig: require('./round-check-blue-big.png'),
    homeActive: require('./home-active.png'),
    homeInActive: require('./home-inactive.png'),
    userActive: require('./user-active.png'),
    userInActive: require('./user-inactive.png'),
    editSquare: require('./edit-square.png'),
    logout: require('./logout.png'),
    chevronRight: require('./chevron-right.png'),
    arrowLeft: require('./arrow-left.png'),
    pencil: require('./pencil.png'),
    wavingHand: require('./waving-hand.png'),
    wrong: require('./wrong.png'),
    check: require('./check.png'),
    userCircle: require('./circle-user.png'),
    mapPin : require('./map-pin.png'),
    wallet : require('./wallet.png'),
    cart: require('./cart.png'),
    cartWhite: require('./cart-white.png'),
    searchActive: require('./search-active.png'),
    search: require('./search.png'),
    camera: require('./camera.png'),
    purchased: require('./purchased.png'),
    download: require('./download.png'),
    history: require('./history.png'),
    clockExpired: require('./clock-expired.png'),
    question: require('./question.png')
};
